### ISSUE TITLE
the pretrained model file

### ISSUE THREAD

**Issue by Tengfei-Wang** [linhdvu14/vggvox-speaker-identification#4]
Hi,
Thanks for sharing your code. 
I noticed that the pretrained model file provided by original author is of .mat format, while yours is a .h5 file. Could you please share with me how you convert a matlab .mat file to the h5 filie? I need to convert another .mat file to h5, but I have encountered some difficulties.
Thanks.

**Comment by linhdvu14** [comment]
What I did was writing the weights to a Matlab struct, read back to Python, restore model weights then export to h5. Unfortunately I no longer keep the code, but I think it's quite similar to ![this tutorial](https://docs.scipy.org/doc/scipy/reference/tutorial/io.html).

**Comment by AbdulMoizzz** [comment]
Hi,
Could you please provide the link to this tutorial again. This link seems to be broken.
Thanks.

**Comment by linhdvu14** [comment]
It's this one: https://docs.scipy.org/doc/scipy/reference/tutorial/io.html

**Comment by AbdulMoizzz** [comment]
Thank you.
